apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: wordpress
  name: wordpress-svc
  namespace: poly
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: wordpress
  type: LoadBalancer
